# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import request_validate_pb2 as request__validate__pb2


class ValidateRequestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestValidation = channel.unary_unary(
            "/ValidateRequest/RequestValidation",
            request_serializer=request__validate__pb2.EngineRequest.SerializeToString,
            response_deserializer=request__validate__pb2.EngineResponse.FromString,
        )


class ValidateRequestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestValidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ValidateRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RequestValidation": grpc.unary_unary_rpc_method_handler(
            servicer.RequestValidation,
            request_deserializer=request__validate__pb2.EngineRequest.FromString,
            response_serializer=request__validate__pb2.EngineResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ValidateRequest", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ValidateRequest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestValidation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ValidateRequest/RequestValidation",
            request__validate__pb2.EngineRequest.SerializeToString,
            request__validate__pb2.EngineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
